
name: Publish pub.dev

on:
  push:
    branches:   
      - master
jobs:
  build:
    if: github.repository == 'PDFTron/pdftron-flutter'
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup credentials
      run: | 
        mkdir -p ~/.pub-cache 
        cat <<EOF > ~/.pub-cache/credentials.json
        {
          "accessToken":"${{ secrets.ACCESSTOKEN }}",
          "refreshToken":"${{ secrets.REFRESHTOKEN }}",
          "idToken":"${{ secrets.IDTOKEN }}",
          "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
          "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
          "expiration": ${{ secrets.EXPIRATION }}
        }
        EOF
    - name: Publish package
      run: pub publish -f